stages:
  - build

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  rules:
    - exists:
        - main
  script:
    - apt-get update && apt-get install -y gnupg
    - curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o microsoft.asc.gpg
    - gpg --batch --yes --delete-keys microsoft.asc
    - mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
    - echo "deb [signed-by=/etc/apt/trusted.gpg.d/microsoft.asc.gpg] https://packages.microsoft.com/repos/microsoft-debian-gpg-repo stable main" > /etc/apt/sources.list.d/microsoft.list
    - apt-get update && apt-get install -y apt-transport-https
    - apt-get update && apt-get install -y dotnet-sdk-6.0
    - dotnet tool install -g Microsoft.Maui.Check

    # Install MAUI workload
    - dotnet workload install maui

    # Build
    - dotnet build MqttMauiApp/MqttMauiApp.csproj -c Release -f:net6.0-windows10.0.19041.0

