stages:
  - build

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  rules:
    - exists:
        - main
  script:
    # Install MAUI workload
    - dotnet workload install maui

    # Build
    - dotnet build MqttMauiApp/MqttMauiApp.csproj -c Release -f:net6.0-windows10.0.19041.0

